name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/simplemindedshellmcp/
    permissions:
      id-token: write  # Required for Trusted Publishing
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.13

      - name: Build package
        run: uv build --python 3.13
        working-directory: mcp-server

      - name: Verify package
        run: |
          uvx twine check mcp-server/dist/*

      - name: Publish to PyPI
        run: uv publish
        working-directory: mcp-server
